# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  annotations:
    argocd.argoproj.io/sync-wave: "0"
data:
  config.properties: |
    database.url=postgresql-service:5432
    cache.url=redis-service:6379