apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 80