apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: postgresql
  ports:
  - port: 5432
    targetPort: 80