apiVersion: v1
kind: Service
metadata:
  name: redis-service
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 80